Repository cloudnode-pro/web-ts, pull requests merged in 2025-03, with the labels that each got.

#2 Add CI
  .github/CODEOWNERS
  .github/dependabot.yaml
  .github/workflows/ci.yaml
  .github/workflows/codeql.yaml
  package.json
Labels: enhancement

#3 Reformat code
  src/Request.ts
  src/ServerErrorRegistry.ts
  src/response/JsonResponse.ts
  src/response/Response.ts
Labels: enhancement

#7 Expose request remote IP
  package-lock.json
  package.json
  src/Request.ts
  src/Server.ts
  src/index.ts
  src/response/index.ts
Labels: feature

#11 Alphabetically sort entries in index files for consistency
  generateIndices.sh
  src/index.ts
  src/response/index.ts
  src/routing/index.ts
Labels: enhancement

#10 Make header case and order consistent
  src/Request.ts
  src/Server.ts
  src/response/BufferResponse.ts
  src/response/EmptyResponse.ts
  src/response/Response.ts
Labels: enhancement

#14 Fix Node.js `main` entry point
  package.json
Labels: bug

#13 Added request method and path route
  src/routing/EndpointRoute.ts
Labels: feature

#16 Auto commit indices changes with GitHub actions
  .github/workflows/ci.yaml
  src/index.ts
  src/routing/index.ts
Labels: enhancement

#24 Close server gracefully
  src/Server.ts
Labels: priority:1

#32 Made error registry on Server public
  src/Server.ts
Labels: priority:1

#17 Set JSON content type on JsonResponse
  src/response/JsonResponse.ts
Labels: priority:2

#23 Enable using function for server error registry responses
  src/Server.ts
  src/ServerErrorRegistry.ts
Labels: priority:2

#37 Fix CI
  .github/workflows/ci.yaml
Labels: priority:1

#38 Ensure consistent sort order using `LC_ALL=C`
  generateIndices.sh
Labels: priority:3

#33 Parsing of request cookies and Cookie class for Set-Cookie
  src/Cookie.ts
  src/Request.ts
  src/index.ts
  src/response/Response.ts
Labels: priority:1

#36 Match HEAD requests if the expected method is GET
  src/routing/EndpointRoute.ts
Labels: priority:2

#39 Automatic support for preconditions in HEAD & GET requests
  src/Server.ts
  src/ServerErrorRegistry.ts
  src/response/Response.ts
Labels: priority:2

#40 Add server events
  src/Server.ts
Labels: priority:1

#42 Add ThrowableResponse
  src/Server.ts
  src/response/ThrowableResponse.ts
  src/response/index.ts
Labels: priority:1

#41 Improve server close and listen
  src/Server.ts
Labels: priority:1

#30 Request authentication and authorisation
  src/Request.ts
  src/Server.ts
  src/ServerErrorRegistry.ts
  src/auth/AuthenticatedRequest.ts
  src/auth/Authenticator.ts
  src/auth/Authorisation.ts
  src/auth/Permissible.ts
  src/auth/Permission.ts
  src/auth/PermissionGroup.ts
  src/auth/index.ts
  src/index.ts
  src/response/BufferResponse.ts
  src/response/EmptyResponse.ts
  src/response/JsonResponse.ts
  src/response/Response.ts
  src/response/TextResponse.ts
  src/response/ThrowableResponse.ts
  src/routing/EndpointRoute.ts
  src/routing/Route.ts
  src/routing/RouteRegistry.ts
Labels: priority:1
